### ISSUE TITLE
figure 8 issue

### ISSUE THREAD

**Issue by katyhuff** [arfc/2021-04-nm-illinois#51]
From @munkm 

> I noticed also that the figure of Lifecycle Carbon Emissions (Figure 8 in the PDF) says that it is plotting all scenarios, but doesn't include the XNn scenarios in the legend. Either the figure label or the figure should be updated to either remedy the omission or clarify why it isn't included in the figure.

This issue can be closed with a PR that handles this concern.

**Comment by samgdotson** [comment]
closed by #50
